const categories = [
  "Healthcare Practitioners and Technical Occupations",
  "Healthcare Support Occupations",
  "Business, Executive, Management, and Financial Occupations",
  "Architecture and Engineering Occupations",
  "Education, Training, and Library Occupations",
  "IT Professional Occupations",
  "Other Professional Occupations",
  "Office and Administrative Support Occupations",
  "Services Occupations",
  "Agriculture, Maintenance, Repair, and Skilled Crafts Occupations",
  "Transportation Occupations",
  "Other Occupations",
];

const subCategories = {
  "Healthcare Practitioners and Technical Occupations": [
    "Chiropractor",
    "Dentist",
    "Dietitian or Nutritionist",
    "Optometrist",
    "Pharmacist",
    "Physician",
    "Physician Assistant",
    "Podiatrist",
    "Registered Nurse",
    "Therapist",
    "Veterinarian",
    "Health Technologist or Technician",
    "Other Healthcare Practitioners and Technical Occupation",
  ],
  "Healthcare Support Occupations": [
    "Nursing, Psychiatric, or Home Health Aide",
    "Occupational and Physical Therapist Assistant or Aide",
    "Other Healthcare Support Occupation",
  ],
  "Business, Executive, Management, and Financial Occupations": [
    "Chief Executive",
    "General and Operations Manager",
    "Advertising, Marketing, Promotions, Public Relations, and Sales Manager",
    "Operations Specialties Manager (e.g., IT or HR Manager)",
    "Construction Manager",
    "Engineering Manager",
    "Accountant, Auditor",
    "Business Operations or Financial Specialist",
    "Business Owner",
    "Other Business, Executive, Management, Financial Occupation",
  ],
  "Architecture and Engineering Occupations": [
    "Architect, Surveyor, or Cartographer",
    "Engineer",
    "Other Architecture and Engineering Occupation",
  ],
  "Education, Training, and Library Occupations": [
    "Postsecondary Teacher (e.g., College Professor)",
    "Primary, Secondary, or Special Education School Teacher",
    "Other Teacher or Instructor",
    "Other Education, Training, and Library Occupation",
  ],
  "IT Professional Occupations": [
    "Network Administrator",
    "UI/UX Designer",
    "Mobile App Developer",
    "System Software Developer",
    "Web Developer",
    "Database administrator",
    "Data analyst",
    "IT security specialist",
  ],
  "Other Professional Occupations": [
    "Arts, Design, Entertainment, Sports, and Media Occupations",
    "Computer Specialist, Mathematical Science",
    "Counselor, Social Worker, or Other Community and Social Service Specialist",
    "Lawyer, Judge",
    "Life Scientist (e.g., Animal, Food, Soil, or Biological Scientist, Zoologist)",
    "Physical Scientist (e.g., Astronomer, Physicist, Chemist, Hydrologist)",
    "Religious Worker (e.g., Clergy, Director of Religious Activities or Education)",
    "Social Scientist and Related Worker",
    "Other Professional Occupation",
  ],
  "Office and Administrative Support Occupations": [
    "Supervisor of Administrative Support Workers",
    "Financial Clerk",
    "Secretary or Administrative Assistant",
    "Material Recording, Scheduling, and Dispatching Worker",
    "Other Office and Administrative Support Occupation",
  ],
  "Services Occupations": [
    "Protective Service (e.g., Fire Fighting, Police Officer, Correctional Officer)",
    "Chef or Head Cook",
    "Cook or Food Preparation Worker",
    "Food and Beverage Serving Worker (e.g., Bartender, Waiter, Waitress)",
    "Building and Grounds Cleaning and Maintenance",
    "Personal Care and Service (e.g., Hairdresser, Flight Attendant, Concierge)",
    "Sales Supervisor, Retail Sales",
    "Retail Sales Worker",
    "Insurance Sales Agent",
    "Sales Representative",
    "Real Estate Sales Agent",
    "Other Services Occupation",
  ],
  "Agriculture, Maintenance, Repair, and Skilled Crafts Occupations": [
    "Construction and Extraction (e.g., Construction Laborer, Electrician)",
    "Farming, Fishing, and Forestry",
    "Installation, Maintenance, and Repair",
    "Production Occupations",
    "Other Agriculture, Maintenance, Repair, and Skilled Crafts Occupation",
  ],
  "Transportation Occupations": [
    "Aircraft Pilot or Flight Engineer",
    "Motor Vehicle Operator (e.g., Ambulance, Bus, Taxi, or Truck Driver)",
    "Other Transportation Occupation",
  ],
  "Other Occupations": ["Homemaker", "Other Occupation", "Not Applicable"],
};

export const getCategories = () => categories;

export const getSubCategories = (category) => subCategories[category];
